// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.asptttoulousenatation.client.resources;

import com.google.gwt.resources.client.CssResource;

public interface ASPTT_ProtoCss extends CssResource {

	String bloc();

	@ClassName("bloc-content")
	String blocContent();

	@ClassName("bloc-title")
	String blocTitle();

	@ClassName("bloc-title-link")
	String blocTitleLink();

	@ClassName("calendar-evt")
	String calendarEvt();

	String clair();

	@ClassName("content-content-title")
	String contentContentTitle();

	String counter();

	String even();

	String fonce();

	String header();

	@ClassName("header-login")
	String headerLogin();
	
	@ClassName("header-login-omnisport")
	String headerLoginOmnisport();
	
	@ClassName("header-photo")
	String headerPhoto();

	@ClassName("header-login-connexion")
	String headerLoginConnexion();

	@ClassName("header-login-inscription-panel")
	String headerLoginInscriptionPanel();
	
	@ClassName("header-login-inscription")
	String headerLoginInscription();

	@ClassName("header-login-sub-line")
	String headerLoginSubLine();

	@ClassName("menu-b")
	String menuB();

	@ClassName("menu-b-title")
	String menuBTitle();

	@ClassName("menu-g")
	String menuG();

	@ClassName("menu-g-sub")
	String menuGSub();

	@ClassName("menu-g-title")
	String menuGTitle();

	@ClassName("menu-g-title-first")
	String menuGTitleFirst();

	@ClassName("menu-g-sub-mouseover")
	String menuGSubMouseOver();
	
	@ClassName("menu-h")
	String menuH();

	@ClassName("menu-h-image")
	String menuHImage();

	@ClassName("menu-h-title")
	String menuHTitle();

	String odd();

	String page();

	String root();

	String tetiere();

	@ClassName("text-fonce")
	String textFonce();

	@ClassName("text-gris")
	String textGris();

	String title();

	@ClassName("login")
	String login();

	@ClassName("login-title")
	String loginTitle();

	@ClassName("login-content")
	String loginContent();

	@ClassName("login-button")
	String loginButton();

	@ClassName("login-close")
	String loginClose();

	@ClassName("odd-header")
	String oddHeader();

	@ClassName("even-header")
	String evenHeader();

	@ClassName("header-panel")
	String headerPanel();

	@ClassName("header-panel-header")
	String headerPanelHeader();

	@ClassName("header-panel-content")
	String headerPanelContent();

	@ClassName("login-header")
	String loginHeader();

	@ClassName("user-header-goBackPublic-button")
	String goBackPublicButton();

	@ClassName("user-header")
	String userHeader();

	@ClassName("logout-panel")
	String logoutPanel();

	@ClassName("logout-panel-label")
	String logoutLabelPanel();

	@ClassName("login-forget-button")
	String loginForgetButton();

	@ClassName("login-forget-label")
	String loginForgetLabel();
	
	@ClassName("main-body")
	String mainBody();
	
	@ClassName("main-content")
	String mainContent();

	@ClassName("header-logo")
	String headerLogo();

	@ClassName("userspace-header")
	String userSpaceHeader();

	@ClassName("userspace-menu")
	String userSpaceMenu();

	@ClassName("userspace-content")
	String userSpaceContent();

	@ClassName("userspace-page")
	String userSpacePage();

	@ClassName("userspace-menu-button")
	String userSpaceMenuButton();

	@ClassName("userspace-content-label")
	String userSpaceContentLabel();

	@ClassName("userspace-content-list")
	String userSpaceContentList();

	@ClassName("userspace-content-list-selected")
	String userSpaceContentListSelected();

	@ClassName("userspace-content-list-odd")
	String userSpaceContentListOdd();

	@ClassName("userspace-area-edition")
	String userSpaceAreaEdition();

	@ClassName("userspace-content-label-2")
	String userSpaceContentLabel2();

	@ClassName("userspace-edition")
	String userSpaceContentEdition();

	@ClassName("userspace-content-competition-day-list")
	String userSpaceContentCompetitionDayList();

	@ClassName("userspace-calendar")
	String userSpaceCalendar();

	@ClassName("userspace-calendar-day")
	String userSpaceCalendarDay();

	@ClassName("userspace-calendar-day-label")
	String userSpaceCalendarDayLabel();

	@ClassName("userspace-calendar-competition-label")
	String userSpaceCalendarCompetitionLabel();

	@ClassName("userspace-calendar-header")
	String userSpaceCalendarHeader();

	@ClassName("userspace-calendar-nav")
	String userSpaceCalendarNav();

	@ClassName("userspace-calendar-title")
	String userSpaceCalendarTitle();

	@ClassName("userspace-calendar-competition-day-value")
	String userSpaceCalendarCompetitionDayValue();

	@ClassName("userspace-calendar-competition-day-button")
	String userSpaceCalendarCompetitionDayButton();

	@ClassName("document-widget")
	String documentWidget();

	@ClassName("area-document-list")
	String areaDocumentList();

	@ClassName("area-document-item")
	String areaDocumentItem();
	
	@ClassName("area-document-list-title")
	String areaDocumentListTitle();
	
	@ClassName("partner-panel")
	String partnerPanel();
	
	@ClassName("delete-button")
	String deleteButton();
	
	@ClassName("edit-button")
	String editButton();
	
	@ClassName("add-button")
	String addButton();
	
	@ClassName("button-bar")
	String buttonBar();
	
	@ClassName("create-menu-button")
	String createMenuButton();
	
	@ClassName("menu-sub")
	String menuSub();
	
	@ClassName("menu-sub-label")
	String menuSubLabel();
	
	@ClassName("userspace-area-edition-edit")
	String userSpaceAreaEditionEdit();
	
	@ClassName("userspace-area-edition-edit-title")
	String userSpaceAreaEditionEditTitle();
	
	@ClassName("userspace-area-menu-selection")
	String userSpaceAreaMenuSelection();
	
	@ClassName("userspace-area-menu-selection-title")
	String userSpaceAreaMenuSelectionTitle();
	
	@ClassName("new-page-button")
	String newPageButton();
	
	@ClassName("subscription-button-bar")
	String subscriptionButtonBar();

	@ClassName("subscription-previous")
	String subscriptionPreviousButton();

	@ClassName("subscription-next")
	String subscriptionNextButton();
	
	@ClassName("day-panel")
	String dayPanel();
	
	@ClassName("day-previous")
	String dayPreviousButton();
	
	@ClassName("day-next")
	String dayNextButton();
	
	@ClassName("day-label")
	String dayLabel();
	
	@ClassName("swimmer-stat-action-valid")
	String swimmerStatActionsValid();
	
	@ClassName("swimmer-stat-action-calendar")
	String swimmerStatActionsCalendar();
	
	@ClassName("popup-close-button")
	String popupCloseButton();
	
	@ClassName("titre-panel")
	String titrePanel();
	
	@ClassName("accueil-titre")
	String accueilTitre();
	
	@ClassName("old-version")
	String oldVersion();
	
	@ClassName("actu-bloc")
	String actuBloc();
	
	@ClassName("actu-bloc-header")
	String actuBlocHeader();
	
	@ClassName("actu-bloc-content")
	String actuBlocContent();
	
	@ClassName("more-actu-button")
	String moreActuButton();
}