// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.asptttoulousenatation.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface ASPTT_ProtoCss extends CssResource {
  
  String bloc();
  
  @ClassName("bloc-content")
  String blocContent();
  
  @ClassName("bloc-title")
  String blocTitle();
  
  @ClassName("bloc-title-link")
  String blocTitleLink();
  
  @ClassName("calendar-evt")
  String calendarEvt();
  
  String clair();
  
  @ClassName("content-content-title")
  String contentContentTitle();
  
  String counter();
  
  String even();
  
  String fonce();
  
  String header();
  
  @ClassName("header-login")
  String headerLogin();
  
  @ClassName("header-login-connexion")
  String headerLoginConnexion();
  
  @ClassName("header-login-inscription")
  String headerLoginInscription();
  
  @ClassName("header-login-sub-line")
  String headerLoginSubLine();
  
  @ClassName("menu-b")
  String menuB();
  
  @ClassName("menu-b-title")
  String menuBTitle();
  
  @ClassName("menu-g")
  String menuG();
  
  @ClassName("menu-g-sub")
  String menuGSub();
  
  @ClassName("menu-g-title")
  String menuGTitle();
  
  @ClassName("menu-g-title-first")
  String menuGTitleFirst();
  
  @ClassName("menu-g-sub-mouseover")
  String menuGSubMouseOver();
  
  @ClassName("menu-h")
  String menuH();
  
  @ClassName("menu-h-image")
  String menuHImage();
  
  @ClassName("menu-h-title")
  String menuHTitle();
  
  String odd();
  
  String page();
  
  String root();
  
  String tetiere();
  
  @ClassName("text-fonce")
  String textFonce();
  
  @ClassName("text-gris")
  String textGris();
  
  String title();
  
  @ClassName("login")
  String login();
  
  @ClassName("login-title")
  String loginTitle();

  @ClassName("login-content")
  String loginContent();

  @ClassName("login-button")
  String loginButton();
  
  @ClassName("login-close")
  String loginClose();
  
  @ClassName("odd-header")
  String oddHeader();
  
  @ClassName("even-header")
  String evenHeader();
  
  @ClassName("header-panel")
  String headerPanel();
  
  @ClassName("header-panel-header")
  String headerPanelHeader();

  @ClassName("header-panel-content")
  String headerPanelContent();
  
  @ClassName("login-header")
  String loginHeader();
  
  @ClassName("user-header-goBackPublic-button")
  String goBackPublicButton();
  
  @ClassName("user-header")
  String userHeader();
  
  @ClassName("logout-panel")
  String logoutPanel();
  
  @ClassName("logout-panel-label")
  String logoutLabelPanel();
  
  @ClassName("login-forget-button")
  String loginForgetButton();
  
  @ClassName("login-forget-label")
  String loginForgetLabel();
  
  @ClassName("group-list")
  String groupList();
  
  @ClassName("group-edition")
  String groupEdition();
}