// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package fr.asptttoulousenatation.client.resources;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface ASPTT_ProtoCss extends CssResource {
  
  String bloc();
  
  @ClassName("bloc-content")
  String blocContent();
  
  @ClassName("bloc-title")
  String blocTitle();
  
  @ClassName("calendar-evt")
  String calendarEvt();
  
  String clair();
  
  @ClassName("content-content-title")
  String contentContentTitle();
  
  String counter();
  
  String even();
  
  String fonce();
  
  String header();
  
  @ClassName("header-login")
  String headerLogin();
  
  @ClassName("header-login-connexion")
  String headerLoginConnexion();
  
  @ClassName("header-login-inscription")
  String headerLoginInscription();
  
  @ClassName("menu-b")
  String menuB();
  
  @ClassName("menu-b-title")
  String menuBTitle();
  
  @ClassName("menu-g")
  String menuG();
  
  @ClassName("menu-g-sub")
  String menuGSub();
  
  @ClassName("menu-g-title")
  String menuGTitle();
  
  @ClassName("menu-h")
  String menuH();
  
  @ClassName("menu-h-image")
  String menuHImage();
  
  @ClassName("menu-h-title")
  String menuHTitle();
  
  String odd();
  
  String page();
  
  String root();
  
  String tetiere();
  
  @ClassName("text-fonce")
  String textFonce();
  
  @ClassName("text-gris")
  String textGris();
  
  String title();
}

