// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.asptttoulousenatation.core.client.resource;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
public interface AutohitsCoreCss extends CssResource {
  
  @ClassName("autohits-banner")
  String autohitsBanner();
  
  @ClassName("autohits-description")
  String autohitsDescription();
  
  @ClassName("autohits-disclosureLayoutPanel")
  String autohitsDisclosureLayoutPanel();
  
  @ClassName("autohits-disclosureLayoutPanel-content")
  String autohitsDisclosureLayoutPanelContent();
  
  @ClassName("autohits-disclosureLayoutPanel-header")
  String autohitsDisclosureLayoutPanelHeader();
  
  @ClassName("autohits-home-button")
  String autohitsHomeButton();
  
  @ClassName("autohits-home-button-connexion")
  String autohitsHomeButtonConnexion();
  
  @ClassName("autohits-home-button-subscription")
  String autohitsHomeButtonSubscription();
  
  @ClassName("autohits-home-button-subscription-validate")
  String autohitsHomeButtonSubscriptionValidate();
  
  @ClassName("autohits-PopupLayout")
  String autohitsPopupLayout();
  
  String close();
  
  String content();
  
  String header();
  
  String text();
  
  @ClassName("user-email")
  String userEmail();
}

